SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================
-- Author:		<Julius Abate>
-- Create date: <April 7, 2016>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [fdt].[fact_and_dim_labs]
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED 

   IF OBJECT_ID('fdt.[Fact and Dim Lab Result]') IS NOT NULL
		DROP TABLE fdt.[Fact and Dim Lab Result]

   IF OBJECT_ID('fdt.[Fact and Dim Lab Order]') IS NOT NULL 
		DROP TABLE fdt.[Fact and Dim Lab Order]

   SELECT lab_res_key
      ,lab_ord_key
      ,per_mon_id
      --,obx_seq_num --Appears to be an order of evaluation possibly
      --,value_type --Two character code, not sure what it means
      ,obs_id AS [Observation ID]
      ,loinc_code AS [LOINC Code]
      ,observ_value AS [Order Value]
      ,value_long AS [Result Value]
      --,abnorm_flags
      ,obs_date_time AS [Observation Date]
      ,result_desc AS [Lab Description]
      ,delete_ind AS [Result Deleted]
      ,create_timestamp AS [Result Date]
      ,clinical_name AS [Lab Clinical Name]
      ,result_comment AS [Result Comments]
      ,hiv_pos_res AS [HIV Positive]
      ,hiv_inc_res AS [HIV Inconclusive]
      ,t_cell_test AS [T-Cell Tests]
      ,cd4_cell_range AS [CD4 Range]
      ,hb_a1c_range AS [A1C Range]
      ,pre_diab_flag AS [Pre-Diabetic]
  INTO fdt.[Fact and Dim Lab Result]
  FROM Prod_Ghost.dwh.data_lab_result


  SELECT lab_ord_key
      ,enc_appt_key
      ,per_mon_id
      ,ordering_prov_key
      ,create_user_key
      ,mod_user_key
      ,test_status AS [Test Status]
      ,ngn_status AS [Order NG Status]
      ,test_desc AS [Test Description]
      ,delete_ind AS [Deleted Test]
      --,order_priority --Need to understand priorities better before adding to the model
      ,time_entered AS [Order Date]
      --,billing_type
      --,clinical_info
      ,cancel_reason AS [Cancellation Reason]
      ,ufo_num AS [UFO Num]
      ,lab_id AS [Lab ID]
      ,generated_by AS [Generated By]
      ,order_type AS [Order Type]
      --,documents_ind
      --,intrf_msg
      ,completed_ind AS [Order Status]
      ,hiv_test_count AS [HIV Test]
  INTO fdt.[Fact and Dim Lab Order]
  FROM Prod_Ghost.dwh.data_lab_order



END
GO
