CREATE TABLE [dwh].[data_appointment_ecw]
(
[ecw_enc_key] [int] NOT NULL,
[enc_nbr] [int] NOT NULL,
[person_id] [int] NOT NULL,
[location_id] [int] NULL,
[provider_rendering_id] [int] NULL,
[rendPrId] [int] NULL,
[pcp_id] [int] NULL,
[user_appt_created] [int] NULL,
[appt_create_date] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[appt_create_time] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[enc_date] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[appt_start_time] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[appt_end_time] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status_long] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[visit_status] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VisitType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[nbr_bill_enc] [int] NULL,
[all_enc_count] [int] NULL,
[all_appt_count] [int] NOT NULL,
[appt_noshow_ind] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[appt_cancel_ind] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[appt_reschedule_ind] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[nbr_appt_no_show] [int] NULL,
[nbr_appt_cancel] [int] NULL,
[nbr_appt_rescheduled] [int] NULL,
[nbr_pcp_appts] [int] NULL,
[nbr_nonpcp_appts] [int] NULL,
[days_to_appt] [int] NULL,
[appt_duration] [int] NULL,
[appt_book_date] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[nbr_appt_future] [int] NULL,
[pay1_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pay2_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pay3_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pcp_appointment] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
