CREATE TABLE [dwh].[data_labs]
(
[lab_res_key] [int] NOT NULL IDENTITY(1, 1),
[lab_ord_key] [int] NOT NULL,
[enc_appt_key] [int] NULL,
[per_mon_id] [int] NULL,
[person_key] [int] NULL,
[enc_id] [uniqueidentifier] NULL,
[person_id] [uniqueidentifier] NULL,
[ordering_prov_key] [int] NULL,
[ordering_prov_id] [uniqueidentifier] NULL,
[ordering_provider_name] [varchar] (52) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[create_user_key] [int] NULL,
[create_user_id] [int] NULL,
[create_user_name] [varchar] (92) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mod_user_id] [int] NOT NULL,
[mod_user_key] [int] NULL,
[mod_user_name] [varchar] (92) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[order_num] [uniqueidentifier] NOT NULL,
[test_status] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ngn_status] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[test_desc] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_delete_ind] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[order_control] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[order_priority] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[time_entered] [datetime] NULL,
[spec_action_code] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billing_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[clinical_info] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cancel_reason] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ufo_num] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[lab_id] [int] NULL,
[order_create_date] [datetime] NOT NULL,
[order_modify_date] [datetime] NOT NULL,
[generated_by] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[order_type] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[documents_ind] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[intrf_msg] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ng_completed_ind] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[hiv_test_count] [int] NOT NULL,
[unique_obr_num] [uniqueidentifier] NULL,
[value_type] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[obs_id] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[loinc_code] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[observ_value] [varchar] (608) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cleaned_value] [decimal] (10, 2) NULL,
[units] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref_range] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[abnorm_flags] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[nature_abnorm_chk1] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[observ_result_stat] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_change_dt] [datetime] NULL,
[obs_date_time] [datetime] NULL,
[prod_id_code1] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prod_id_code1_txt] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[signed_off_ind] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[result_desc] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[res_delete_ind] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[comment_ind] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[result_seq_num] [int] NULL,
[created_by] [int] NULL,
[result_date] [datetime] NULL,
[modified_by] [int] NULL,
[result_mod_date] [datetime] NULL,
[clinical_name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[units_batt_id] [varchar] (2180) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hiv_pos_res] [int] NOT NULL,
[hiv_inc_res] [int] NOT NULL,
[t_cell_test] [int] NOT NULL,
[order_rank] [int] NULL,
[value_long] [varchar] (51) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cd4_cell_range] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hb_a1c_range] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pre_diab_flag] [int] NOT NULL,
[Recency] [bigint] NULL,
[count_distinct_order] [int] NOT NULL,
[lab_result_dx] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[type] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[range] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[count_complete_order] [int] NOT NULL
) ON [PRIMARY]
GO
