CREATE TABLE [dwh].[data_case_managment]
(
[per_mon_id] [int] NULL,
[first_mon_date] [date] NULL,
[Enc Id] [uniqueidentifier] NOT NULL,
[Case Management Status Active] [int] NULL,
[Case Management Status Inactive] [int] NULL,
[Inactive Date] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Referal From Outsite Lifelong] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ambulatory Disability] [int] NULL,
[Cognitive Disability] [int] NULL,
[Homelessness-Current] [int] NULL,
[Self-Care Disability] [int] NULL,
[AOD Use/Abuse - History*] [int] NULL,
[Complex Medical Needs] [int] NULL,
[Homelessness-History] [int] NULL,
[Trauma/Abuse-History] [int] NULL,
[AOD Use/Abuse - Current*] [int] NULL,
[Violence/Abuse-Current] [int] NULL,
[Independent Living Disability*] [int] NULL,
[Migrant/Seasonal Worker] [int] NULL,
[Behavioral Health Dx] [int] NULL,
[ED-High Utilizer] [int] NULL,
[Incarceration History] [int] NULL,
[Low Literacy] [int] NULL,
[Chronic Disease Dx] [int] NULL,
[Hearing Disability*] [int] NULL,
[Visual Disability*] [int] NULL,
[Language Prefered Not English] [int] NULL,
[Staff FullName] [varchar] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Recency] [bigint] NULL
) ON [PRIMARY]
GO
