CREATE TABLE [dwh].[data_lab_order]
(
[lab_ord_key] [int] NOT NULL IDENTITY(1, 1),
[enc_appt_key] [int] NULL,
[per_mon_id] [int] NULL,
[ordering_prov_key] [int] NULL,
[create_user_key] [int] NULL,
[mod_user_key] [int] NULL,
[order_num] [uniqueidentifier] NOT NULL,
[test_status] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ngn_status] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[test_desc] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[delete_ind] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[order_control] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[order_priority] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[time_entered] [datetime] NULL,
[spec_action_code] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billing_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[clinical_info] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cancel_reason] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ufo_num] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[lab_id] [int] NULL,
[create_timestamp] [datetime] NOT NULL,
[modify_timestamp] [datetime] NOT NULL,
[generated_by] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[order_type] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[documents_ind] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[intrf_msg] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[completed_ind] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[hiv_test_count] [int] NOT NULL
) ON [PRIMARY]
GO
