CREATE TABLE [dwh].[data_employee_payroll_scd]
(
[employee_key] [int] NOT NULL,
[employee_payroll_key] [int] NOT NULL,
[File Number] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Payroll Name Hx] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[chart_account_key] [int] NULL,
[Pay Date] [date] NULL,
[Home Cost Number - Check] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cost Number Worked In] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Hourly Rate Calculated based on Reg Earnings] [decimal] (38, 6) NULL,
[Salary Calculated (Reg Earnings) Annualized] [decimal] (38, 6) NULL,
[Age_hx] [int] NULL,
[months_since_start_hx] [int] NULL,
[months_since_start_allocated_hx] [int] NULL,
[FTE_hx] [decimal] (38, 6) NULL,
[FTE_allocated_hx] [decimal] (38, 6) NULL,
[Annual Salary ADP not annualized] [decimal] (38, 4) NULL,
[Age_range_cur] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[age_range_cur_sort] [int] NOT NULL,
[Remaining Floating Hrs] [decimal] (38, 4) NULL,
[Remaining Holiday Hrs] [decimal] (38, 4) NULL,
[Remaining LTS Hrs] [decimal] (38, 4) NULL,
[Remaining Sick Hrs] [decimal] (38, 4) NULL,
[Remaining Vacation Hrs] [decimal] (38, 4) NULL,
[FTE_Range_hx] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FTE_Range_hx_sort] [int] NOT NULL,
[FTE_Allocated_Range_hx] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FTE_Allocated_Range_hx_sort] [int] NOT NULL,
[age_range_hx] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[age_range_hx_sort] [int] NOT NULL,
[months_since_start_range_hx] [varchar] (27) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[months_since_start_range_hx_sort] [int] NULL,
[months_since_start_allocated_range_hx] [varchar] (27) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[months_since_start_allocated_range_hx_sort] [int] NULL,
[rate_range_hx] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rate_range_hx_sort] [int] NULL,
[salary_annualized_range_hx] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[salary_annualized_range_hx_sort] [int] NULL,
[rate_range_cur] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rate_range_cur_sort] [int] NULL,
[rate_direct_range_cur] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rate_direct_range_cur_sort] [int] NULL,
[salary_annualized_range_cur] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[salary_annualized_range_cur_sort] [int] NULL,
[salary_not_annualized_range_cur] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[salary_not_annualized_range_cur_sort] [int] NULL,
[OSHPD Category] [varchar] (58) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cn_site_hx] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
