CREATE TABLE [dwh].[data_time_source]
(
[PK_Date] [datetime] NOT NULL,
[Date_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Year] [datetime] NULL,
[Year_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Half_Year] [datetime] NULL,
[Half_Year_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Quarter] [datetime] NULL,
[Quarter_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Trimester] [datetime] NULL,
[Trimester_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Month] [datetime] NULL,
[Month_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ten_Days] [datetime] NULL,
[Ten_Days_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Week] [datetime] NULL,
[Week_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Day_Of_Year] [int] NULL,
[Day_Of_Year_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Day_Of_Half_Year] [int] NULL,
[Day_Of_Half_Year_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Day_Of_Trimester] [int] NULL,
[Day_Of_Trimester_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Day_Of_Quarter] [int] NULL,
[Day_Of_Quarter_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Day_Of_Month] [int] NULL,
[Day_Of_Month_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Day_Of_Ten_Days] [int] NULL,
[Day_Of_Ten_Days_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Day_Of_Week] [int] NULL,
[Day_Of_Week_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Week_Of_Year] [int] NULL,
[Week_Of_Year_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ten_Days_Of_Year] [int] NULL,
[Ten_Days_Of_Year_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ten_Days_Of_Half_Year] [int] NULL,
[Ten_Days_Of_Half_Year_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ten_Days_Of_Trimester] [int] NULL,
[Ten_Days_Of_Trimester_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ten_Days_Of_Quarter] [int] NULL,
[Ten_Days_Of_Quarter_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ten_Days_Of_Month] [int] NULL,
[Ten_Days_Of_Month_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Month_Of_Year] [int] NULL,
[Month_Of_Year_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Month_Of_Half_Year] [int] NULL,
[Month_Of_Half_Year_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Month_Of_Trimester] [int] NULL,
[Month_Of_Trimester_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Month_Of_Quarter] [int] NULL,
[Month_Of_Quarter_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Quarter_Of_Year] [int] NULL,
[Quarter_Of_Year_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Quarter_Of_Half_Year] [int] NULL,
[Quarter_Of_Half_Year_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Trimester_Of_Year] [int] NULL,
[Trimester_Of_Year_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Half_Year_Of_Year] [int] NULL,
[Half_Year_Of_Year_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Year] [datetime] NULL,
[Fiscal_Year_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Half_Year] [datetime] NULL,
[Fiscal_Half_Year_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Quarter] [datetime] NULL,
[Fiscal_Quarter_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Trimester] [datetime] NULL,
[Fiscal_Trimester_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Month] [datetime] NULL,
[Fiscal_Month_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Week] [datetime] NULL,
[Fiscal_Week_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Day] [datetime] NULL,
[Fiscal_Day_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Day_Of_Year] [int] NULL,
[Fiscal_Day_Of_Year_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Day_Of_Half_Year] [int] NULL,
[Fiscal_Day_Of_Half_Year_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Day_Of_Trimester] [int] NULL,
[Fiscal_Day_Of_Trimester_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Day_Of_Quarter] [int] NULL,
[Fiscal_Day_Of_Quarter_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Day_Of_Month] [int] NULL,
[Fiscal_Day_Of_Month_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Day_Of_Week] [int] NULL,
[Fiscal_Day_Of_Week_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Week_Of_Year] [int] NULL,
[Fiscal_Week_Of_Year_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Month_Of_Year] [int] NULL,
[Fiscal_Month_Of_Year_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Month_Of_Half_Year] [int] NULL,
[Fiscal_Month_Of_Half_Year_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Month_Of_Trimester] [int] NULL,
[Fiscal_Month_Of_Trimester_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Month_Of_Quarter] [int] NULL,
[Fiscal_Month_Of_Quarter_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Trimester_Of_Year] [int] NULL,
[Fiscal_Trimester_Of_Year_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Quarter_Of_Year] [int] NULL,
[Fiscal_Quarter_Of_Year_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Quarter_Of_Half_Year] [int] NULL,
[Fiscal_Quarter_Of_Half_Year_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Half_Year_Of_Year] [int] NULL,
[Fiscal_Half_Year_Of_Year_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Relative_days_to_CurrentDate] [int] NULL,
[Relative_months_to_CurrentDate] [int] NULL,
[Relative_weeks_to_CurrentDate] [int] NULL
) ON [PRIMARY]
GO
