CREATE TABLE [dwh].[data_sp_patient_survey]
(
[survey_key] [int] NOT NULL IDENTITY(1, 1),
[enc_num] [numeric] (18, 0) NULL,
[enc_appt_key] [int] NOT NULL,
[survey_q1] [decimal] (18, 0) NULL,
[survey_q2] [decimal] (18, 0) NULL,
[survey_q3] [decimal] (18, 0) NULL,
[survey_q4] [decimal] (18, 0) NULL,
[survey_q5] [decimal] (18, 0) NULL,
[survey_q6] [decimal] (18, 0) NULL,
[survey_q7] [decimal] (18, 0) NULL,
[survey_critical] [int] NOT NULL,
[q1_val] [int] NULL,
[q2_val] [int] NULL,
[q3_val] [int] NULL,
[q4_val] [int] NULL,
[q5_val] [int] NULL,
[q6_val] [int] NULL,
[total_q1] [int] NOT NULL,
[total_q2] [int] NOT NULL,
[total_q3] [int] NOT NULL,
[total_q4] [int] NOT NULL,
[total_q5] [int] NOT NULL,
[total_q6] [int] NOT NULL,
[total_q7] [int] NOT NULL,
[promoter] [int] NOT NULL,
[detractor] [int] NOT NULL,
[comments] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[created] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
