CREATE TABLE [dwh].[data_charge]
(
[enc_id] [uniqueidentifier] NOT NULL,
[enc_key] [int] NOT NULL,
[source_id] [uniqueidentifier] NULL,
[enc_bill_date] [date] NULL,
[begin_date_of_service] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sim_code] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[charge_void_status] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[charge_id] [uniqueidentifier] NOT NULL,
[service_item_id] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cpt4_code_id] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[icd9cm_code_id] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[icd9cm_code_id_2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[icd9cm_code_id_3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[icd9cm_code_id_4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[override_ind] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[user_charge_created] [int] NOT NULL,
[chg_closing_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Charge_Status] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[chg_mod_date] [datetime] NOT NULL,
[zero_bal_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[credit_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Txn_closing_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Txn_batch_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Txn_override_closing_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Txn_post_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[days_chg_close_to_txn_close] [int] NULL,
[days_chg_close_to_txn_post] [int] NULL,
[days_chg_close_to_txn_batch] [int] NULL,
[days_txn_batch_to_txn_post] [int] NULL,
[days_enc_to_chg_close] [int] NULL,
[all_void_and_non_void_charge_amt] [numeric] (19, 2) NOT NULL,
[cob1_amt] [numeric] (19, 2) NOT NULL,
[cob2_amt] [numeric] (19, 2) NOT NULL,
[cob3_amt] [numeric] (19, 2) NOT NULL,
[pat_amt] [numeric] (19, 2) NOT NULL,
[non_void_charge_amt] [numeric] (19, 2) NOT NULL,
[non_enc_rate_charge_amt] [numeric] (19, 2) NULL,
[enc_rate_charge_amt] [numeric] (19, 2) NULL
) ON [PRIMARY]
GO
