CREATE TABLE [etl].[data_adp_roster_payroll]
(
[Home Cost Number - Check] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Cost Number Desc - Check] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Department - Check] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Department Desc - Check] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Location] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Location Code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Hire Source] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Hire Source Code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pay Grade] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pay Frequency] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pay Group Code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pay Group Desc] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rate Amount] [float] NULL,
[Job Title] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Annual Salary] [float] NULL,
[First Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Payroll Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Hire Date] [datetime] NULL,
[Termination Date] [datetime] NULL,
[Race] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSN] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age] [float] NULL,
[Zip/Postal Code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Department] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Data Control] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FTE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Period Beginning Date] [datetime] NULL,
[Period End Date - Check] [datetime] NULL,
[Period Rate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[File Number] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Hourly Rate (001)] [float] NULL,
[Payroll Number] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reversal Indicator - Check] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard Hours] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Regular Hours] [float] NULL,
[All Other Coded Hours] [float] NULL,
[Overtime Hours] [float] NULL,
[Regular Earnings] [money] NULL,
[Other Earnings] [float] NULL,
[Overtime Earnings] [money] NULL,
[Net Pay] [float] NULL,
[Gross Pay] [money] NULL,
[_Hours Coded1] [float] NULL,
[_Hours Coded2] [float] NULL,
[_Hours Coded3] [float] NULL,
[_Hours Coded4] [float] NULL,
[_Hours Coded5] [float] NULL,
[_Hours Coded6] [float] NULL,
[_Hours Coded7] [float] NULL,
[_Hours Coded8] [float] NULL,
[_Hours Coded9] [float] NULL,
[_Hours Coded10] [float] NULL,
[_Hours Coded11] [float] NULL,
[_Hours Coded12] [float] NULL,
[_Hours Coded13] [float] NULL,
[_Hours Coded14] [float] NULL,
[_Hours Coded15] [float] NULL,
[_Hours Coded16] [float] NULL,
[_Hours Coded17] [float] NULL,
[_Hours Coded18] [float] NULL,
[_Hours Coded19] [float] NULL,
[_Hours Coded20] [float] NULL,
[_Hours Coded21] [float] NULL,
[_Hours Coded22] [float] NULL,
[_Hours Coded23] [float] NULL,
[_Hours Coded24] [float] NULL,
[_Hours Coded25] [float] NULL,
[_Hours Coded26] [float] NULL,
[_Hours Coded27] [float] NULL,
[_Hours Coded28] [float] NULL,
[_Hours Coded29] [float] NULL,
[_Hours Coded30] [float] NULL,
[_Hours Coded31] [float] NULL,
[_Hours Coded32] [float] NULL,
[_Earnings Coded1] [float] NULL,
[_Earnings Coded2] [float] NULL,
[_Earnings Coded3] [float] NULL,
[_Earnings Coded4] [float] NULL,
[_Earnings Coded5] [float] NULL,
[_Earnings Coded6] [float] NULL,
[_Earnings Coded7] [float] NULL,
[_Earnings Coded8] [float] NULL,
[_Earnings Coded9] [float] NULL,
[_Earnings Coded10] [float] NULL,
[_Earnings Coded11] [float] NULL,
[_Earnings Coded12] [float] NULL,
[_Earnings Coded13] [float] NULL,
[_Earnings Coded14] [float] NULL,
[_Earnings Coded15] [float] NULL,
[_Earnings Coded16] [float] NULL,
[_Earnings Coded17] [float] NULL,
[_Earnings Coded18] [float] NULL,
[_Earnings Coded19] [float] NULL,
[_Earnings Coded20] [float] NULL,
[_Earnings Coded21] [float] NULL,
[_Earnings Coded22] [float] NULL,
[_Earnings Coded23] [float] NULL,
[_Earnings Coded24] [float] NULL,
[_Earnings Coded25] [float] NULL,
[_Earnings Coded26] [float] NULL,
[_Earnings Coded27] [float] NULL,
[_Earnings Coded28] [float] NULL,
[_Earnings Coded29] [float] NULL,
[_Earnings Coded30] [float] NULL,
[_Earnings Coded31] [float] NULL,
[_Earnings Coded32] [float] NULL,
[_Earnings Coded33] [float] NULL,
[_Earnings Coded34] [float] NULL,
[_Earnings Coded35] [float] NULL,
[_Earnings Coded36] [float] NULL,
[_Earnings Coded37] [float] NULL,
[_Earnings Coded38] [float] NULL,
[_Earnings Coded39] [float] NULL,
[_Earnings Coded40] [float] NULL,
[_Earnings Coded41] [float] NULL,
[_Earnings Coded42] [float] NULL,
[_Earnings Coded43] [float] NULL,
[_Earnings Coded44] [float] NULL,
[_Earnings Coded45] [float] NULL,
[_Earnings Coded46] [float] NULL,
[_Earnings Coded47] [float] NULL,
[_Earnings Coded48] [float] NULL,
[_Earnings Coded49] [float] NULL,
[_Earnings Coded50] [float] NULL,
[_Earnings Coded51] [float] NULL,
[_Earnings Coded52] [float] NULL,
[_Earnings Coded53] [float] NULL,
[_Earnings Coded54] [float] NULL,
[_Earnings Coded55] [float] NULL,
[_Earnings Coded56] [float] NULL,
[_Earnings Coded57] [float] NULL,
[_To_Date Allowed1] [float] NULL,
[_To_Date Allowed2] [float] NULL,
[_To_Date Allowed3] [float] NULL,
[_To_Date Allowed4] [float] NULL,
[_To_Date Allowed5] [float] NULL,
[_To_Date Taken1] [float] NULL,
[_To_Date Taken2] [float] NULL,
[_To_Date Taken3] [float] NULL,
[_To_Date Taken4] [float] NULL,
[_To_Date Taken5] [float] NULL
) ON [PRIMARY]
GO
