CREATE TABLE [fdt].[Fact and Dim Lab Order]
(
[lab_ord_key] [int] NOT NULL IDENTITY(1, 1),
[enc_appt_key] [int] NULL,
[per_mon_id] [int] NULL,
[ordering_prov_key] [int] NULL,
[create_user_key] [int] NULL,
[mod_user_key] [int] NULL,
[Test Status] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order NG Status] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Test Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Deleted Test] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order Date] [datetime] NULL,
[Cancellation Reason] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UFO Num] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Lab ID] [int] NULL,
[Generated By] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order Type] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order Status] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[HIV Test] [int] NOT NULL
) ON [PRIMARY]
GO
