CREATE TABLE [fdt].[Fact Employee Census Payroll]
(
[employee_payroll_key] [int] NOT NULL,
[File Number] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[chart_account_key] [int] NULL,
[Pay Date] [date] NULL,
[Payroll Name Hx] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UDS Person 2015 Tenure] [int] NULL,
[UDS Person 2014 Tenure] [int] NULL,
[Months Since Start Cur] [int] NULL,
[Months Since Start Hx] [int] NULL,
[Months Since Start Allocated Hx] [int] NULL,
[FTE Allocated Hx] [decimal] (38, 6) NULL,
[FTE Hx] [decimal] (38, 6) NULL,
[FTE Current] [numeric] (4, 3) NULL,
[Employee Census Month] [int] NOT NULL,
[Employee Terminated Census Month] [int] NOT NULL,
[Employee Bad Hire Census Month] [int] NOT NULL,
[Employee New Hire Census Month] [int] NOT NULL,
[Total All Hours New Hire] [int] NULL,
[FTE Avg 6m New Hire] [int] NULL,
[UDS Person 2015 Count] [int] NULL,
[UDS Person 2014 Count] [int] NULL,
[UDS Person 2013 Count] [int] NULL,
[Total All Hours Terminated] [int] NULL,
[FTE Terminated 6m Avg] [decimal] (38, 6) NULL,
[FTE New Hire 6m Avg] [decimal] (38, 6) NULL,
[FTE Transfer 6m Avg] [decimal] (38, 6) NULL,
[Employee Transfer Census Month] [int] NOT NULL,
[FTE Avg 6m Terminated] [int] NULL,
[Total All Hours] [decimal] (38, 6) NULL,
[Regular Hours with s/v/f/h] [decimal] (38, 6) NULL,
[Regular Hours] [decimal] (38, 6) NULL,
[All Other Coded Hours] [decimal] (38, 6) NULL,
[Overtime Hours] [decimal] (38, 6) NULL,
[Regular Earnings] [decimal] (38, 6) NULL,
[Other Earnings] [decimal] (38, 6) NULL,
[Overtime Earnings] [decimal] (38, 6) NULL,
[Net Pay] [decimal] (38, 6) NULL,
[Gross Pay] [decimal] (38, 6) NULL,
[Remaining Floating Hrs] [decimal] (38, 4) NULL,
[Remaining Holiday Hrs] [decimal] (38, 4) NULL,
[Remaining LTS Hrs] [decimal] (38, 4) NULL,
[Remaining Sick Hrs] [decimal] (38, 4) NULL,
[Remaining Vacation Hrs] [decimal] (38, 4) NULL,
[_Hours Coded- 0 ] [decimal] (38, 6) NULL,
[_Hours Coded- 11 Penalty Code] [decimal] (38, 6) NULL,
[_Hours Coded- 12 Orientation] [decimal] (38, 6) NULL,
[_Hours Coded- 16 ] [decimal] (38, 6) NULL,
[_Hours Coded- 20 Administrative H] [decimal] (38, 6) NULL,
[_Hours Coded- 21 Committee Hrs] [decimal] (38, 6) NULL,
[_Hours Coded- 25 0.25 bilingual] [decimal] (38, 6) NULL,
[_Hours Coded- 30 Saturday Rate] [decimal] (38, 6) NULL,
[_Hours Coded- 34 ] [decimal] (38, 6) NULL,
[_Hours Coded- 4 Administrative] [decimal] (38, 6) NULL,
[_Hours Coded- 44 Hospital Alta Bates] [decimal] (38, 6) NULL,
[_Hours Coded- 5 Educaiton] [decimal] (38, 6) NULL,
[_Hours Coded- A Hospital] [decimal] (38, 6) NULL,
[_Hours Coded- B Bereavement] [decimal] (38, 6) NULL,
[_Hours Coded- C CME] [decimal] (38, 6) NULL,
[_Hours Coded- CON Conference] [decimal] (38, 6) NULL,
[_Hours Coded- D Double Time] [decimal] (38, 6) NULL,
[_Hours Coded- E Extra Pay] [decimal] (38, 6) NULL,
[_Hours Coded- F Flt/p] [decimal] (38, 6) NULL,
[_Hours Coded- H Holiday] [decimal] (38, 6) NULL,
[_Hours Coded- J Jury] [decimal] (38, 6) NULL,
[_Hours Coded- LTS Long Term Sick] [decimal] (38, 6) NULL,
[_Hours Coded- M Meeting Time] [decimal] (38, 6) NULL,
[_Hours Coded- P Personal Leave] [decimal] (38, 6) NULL,
[_Hours Coded- R Regular] [decimal] (38, 6) NULL,
[_Hours Coded- S Sick] [decimal] (38, 6) NULL,
[_Hours Coded- T Retro Pay] [decimal] (38, 6) NULL,
[_Hours Coded- U ] [decimal] (38, 6) NULL,
[_Hours Coded- V Vacation] [decimal] (38, 6) NULL,
[_Hours Coded- W ] [decimal] (38, 6) NULL,
[_Hours Coded- WRO Weekend Rate OT] [decimal] (38, 6) NULL,
[_Hours Coded- WRT Weekend Rate OT] [decimal] (38, 6) NULL,
[_Hours Coded- 6 SNF Hours] [decimal] (38, 6) NULL,
[_Earnings Coded- 0 ] [decimal] (38, 6) NULL,
[_Earnings Coded- 1 WCME] [decimal] (38, 6) NULL,
[_Earnings Coded- 10 Clinic - On Call] [decimal] (38, 6) NULL,
[_Earnings Coded- 11 Penalty Code] [decimal] (38, 6) NULL,
[_Earnings Coded- 12 Orientation] [decimal] (38, 6) NULL,
[_Earnings Coded- 15 Special Service] [decimal] (38, 6) NULL,
[_Earnings Coded- 16 ] [decimal] (38, 6) NULL,
[_Earnings Coded- 17 Call Alta Bates] [decimal] (38, 6) NULL,
[_Earnings Coded- 18 Call CC County] [decimal] (38, 6) NULL,
[_Earnings Coded- 19 Call-EO-OS] [decimal] (38, 6) NULL,
[_Earnings Coded- 2 Call Nursery] [decimal] (38, 6) NULL,
[_Earnings Coded- 20 Admin H] [decimal] (38, 6) NULL,
[_Earnings Coded- 21 Committee Hrs] [decimal] (38, 6) NULL,
[_Earnings Coded- 25 $0.25 Bilingual] [decimal] (38, 6) NULL,
[_Earnings Coded- 3 Call CHCN] [decimal] (38, 6) NULL,
[_Earnings Coded- 30 Saturday Rate] [decimal] (38, 6) NULL,
[_Earnings Coded- 31 ] [decimal] (38, 6) NULL,
[_Earnings Coded- 32 ] [decimal] (38, 6) NULL,
[_Earnings Coded- 33 ] [decimal] (38, 6) NULL,
[_Earnings Coded- 34 ] [decimal] (38, 6) NULL,
[_Earnings Coded- 39 ] [decimal] (38, 6) NULL,
[_Earnings Coded- 4 Administrative] [decimal] (38, 6) NULL,
[_Earnings Coded- 41 ] [decimal] (38, 6) NULL,
[_Earnings Coded- 44 Hosp AB] [decimal] (38, 6) NULL,
[_Earnings Coded- 45 Call Split Adult] [decimal] (38, 6) NULL,
[_Earnings Coded- 47 Call LMC] [decimal] (38, 6) NULL,
[_Earnings Coded- 48 Call Holiday] [decimal] (38, 6) NULL,
[_Earnings Coded- 5 Education] [decimal] (38, 6) NULL,
[_Earnings Coded- A Hospital] [decimal] (38, 6) NULL,
[_Earnings Coded- B Bereavement] [decimal] (38, 6) NULL,
[_Earnings Coded- C CME] [decimal] (38, 6) NULL,
[_Earnings Coded- CON Conference] [decimal] (38, 6) NULL,
[_Earnings Coded- D Doubletime] [decimal] (38, 6) NULL,
[_Earnings Coded- F Flt/P] [decimal] (38, 6) NULL,
[_Earnings Coded- E Extra Pay] [decimal] (38, 6) NULL,
[_Earnings Coded- FU Follow up] [decimal] (38, 6) NULL,
[_Earnings Coded- H Holiday] [decimal] (38, 6) NULL,
[_Earnings Coded- I Incentive Bonus] [decimal] (38, 6) NULL,
[_Earnings Coded- J Jury] [decimal] (38, 6) NULL,
[_Earnings Coded- L Lead Pay] [decimal] (38, 6) NULL,
[_Earnings Coded- LTS Long Term Sick] [decimal] (38, 6) NULL,
[_Earnings Coded- M Meeting Time] [decimal] (38, 6) NULL,
[_Earnings Coded- N ] [decimal] (38, 6) NULL,
[_Earnings Coded- O On-Call] [decimal] (38, 6) NULL,
[_Earnings Coded- P Personal Leave] [decimal] (38, 6) NULL,
[_Earnings Coded- R Regular] [decimal] (38, 6) NULL,
[_Earnings Coded- S Sick] [decimal] (38, 6) NULL,
[_Earnings Coded- SU Super User] [decimal] (38, 6) NULL,
[_Earnings Coded- T Retro Pay] [decimal] (38, 6) NULL,
[_Earnings Coded- U **] [decimal] (38, 6) NULL,
[_Earnings Coded- V Vacation] [decimal] (38, 6) NULL,
[_Earnings Coded- W ] [decimal] (38, 6) NULL,
[_Earnings Coded- WRO Weekend Rate OT] [decimal] (38, 6) NULL,
[_Earnings Coded- WRT Weekend Rate] [decimal] (38, 6) NULL,
[_Earnings Coded- X Addl 250 Stipend] [decimal] (38, 6) NULL,
[_Earnings Coded- Y 1.25 in Lieu] [decimal] (38, 6) NULL,
[_Earnings Coded- Z 1.50 in Lieu] [decimal] (38, 6) NULL,
[_Earnings Coded- 6 SNF Hours] [decimal] (38, 6) NULL,
[_Earnings Coded- 46 Call Split Peds] [decimal] (38, 6) NULL
) ON [PRIMARY]
GO
