CREATE TABLE [fdt].[Fact Encounter and Appointment]
(
[enc_appt_key] [int] NOT NULL IDENTITY(1, 1),
[user_resource_key] [int] NULL,
[enc_rendering_key] [int] NULL,
[provider_key] [int] NULL,
[location_key] [int] NULL,
[per_mon_id] [int] NULL,
[enc_appt_comp_key] [bigint] NULL,
[event_id] [uniqueidentifier] NULL,
[enc_app_date] [date] NULL,
[user_appt_created] [int] NULL,
[user_checkout] [int] NULL,
[user_readyforprovider] [int] NULL,
[user_enc_created] [int] NULL,
[user_charted] [int] NULL,
[enc_nbr] [numeric] (18, 0) NULL,
[Enc Number] [numeric] (18, 0) NULL,
[event_key] [int] NULL,
[enc_status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[appt_status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[appt_w_pcp_status_txt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[enc_slot_type] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[appt_duration] [int] NULL,
[Appt Duration] [int] NULL,
[appt_time] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Appt Booked with PCP] [int] NOT NULL,
[Appt Booked Not with PCP] [int] NOT NULL,
[All Appt] [int] NOT NULL,
[Appt without a Pt] [int] NOT NULL,
[Appt Kept with Enc] [int] NOT NULL,
[Appt Kept with No Enc] [int] NOT NULL,
[Appt in Future] [int] NOT NULL,
[Appt No Show] [int] NOT NULL,
[Appt No Show with No Patient] [int] NOT NULL,
[Appt Future with No Patient] [int] NOT NULL,
[Appt Cancelled] [int] NOT NULL,
[Appt Deleted] [int] NOT NULL,
[Appt Rescheduled] [int] NOT NULL,
[Enc or Appt] [int] NOT NULL,
[Encounters] [int] NOT NULL,
[Billable Encounters] [int] NOT NULL,
[Non-billable Encounters] [int] NOT NULL,
[Billable Enc with Appt] [int] NOT NULL,
[Non-Billable Enc with Appt] [int] NOT NULL,
[Billable Appts with Enc Kept] [int] NOT NULL,
[Non-Billable Appts with Enc Kept] [int] NOT NULL,
[Days from Booked to Appt] [int] NULL,
[Min from Appt Time to Kept] [int] NULL,
[Min from Kept to Checkout] [int] NULL,
[Min Kept to Ready for Prov] [int] NULL,
[Min from Kept to Charted] [int] NULL,
[Mins from Kept to Charted] [int] NULL,
[Min from Ready for Prov to Checkout] [int] NULL,
[Date of Appointment Made] [date] NULL,
[Payer 1 Name] [varchar] (110) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Payer 1 Financial Class] [varchar] (110) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Payer 2 Name] [varchar] (110) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Payer 2 Financial Class] [varchar] (110) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Payer 3 Name] [varchar] (110) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Payer 3 Financial Class] [varchar] (110) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Diagnosis 1] [varchar] (266) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Diagnosis 2] [varchar] (266) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Diagnosis 3] [varchar] (266) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date of Last Appointment] [date] NULL,
[Date of Last Encounter] [date] NULL
) ON [PRIMARY]
ALTER TABLE [fdt].[Fact Encounter and Appointment] ADD 
CONSTRAINT [enc_appt_keypk23] PRIMARY KEY CLUSTERED  ([enc_appt_key]) ON [PRIMARY]

GO
