CREATE TABLE [fdt].[Dim Employee]
(
[employee_key] [int] NOT NULL IDENTITY(1, 1),
[Cost Nbr Account Code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cost Nbr Account Sub-Code] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cost Nbr Site Code] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cost Nbr Fund] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cost Nbr In/Direct] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cost Nbr Category] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cost Nbr Grant] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cost Nbr] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Department] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Location Code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Location Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Payroll Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[File Number] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Race] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age Current] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[age_cur_sort] [int] NOT NULL,
[Status] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Data Control] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2015 Flu Vaccine Documented as Declined] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[2015 Flu Vaccine Documented as Received] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[2015 TB Documentation] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Job Title] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zip/Postal Code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Manager Last Name First Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Manager Last Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Manager First Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Manager ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rate Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Salary Current] [int] NULL,
[Rate Current] [float] NULL,
[Rate Range Current] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rate_cur_range_sort] [int] NULL,
[Salary Range Current] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[salary_cur_range_sort] [int] NULL,
[Hire Year/Month] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Termination Year/Month] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Termination Reason] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Termination Reason Code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [fdt].[Dim Employee] ADD CONSTRAINT [employee_key_pk3] PRIMARY KEY CLUSTERED  ([employee_key]) ON [PRIMARY]
GO
