CREATE TABLE [fdt].[Fact and Dim Medication]
(
[med_key] [int] NOT NULL IDENTITY(1, 1),
[per_mon_id] [int] NULL,
[appt_loc_key] [int] NULL,
[provider_id] [int] NULL,
[enc_appt_key] [int] NULL,
[first_mon_date] [date] NULL,
[md_id] [numeric] (8, 0) NOT NULL,
[Rx Active Count] [int] NOT NULL,
[Rx Active Flag] [int] NOT NULL,
[Rx Active Prescribed by LifeLong] [int] NOT NULL,
[Rx Active Prescribed Elsewhere] [int] NOT NULL,
[Rx Prescribed Elsewhere Flag] [int] NOT NULL,
[Rx ID] [numeric] (8, 0) NULL,
[gcnsecno] [int] NULL,
[Drug Name] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NDC Class] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Medical Record Number] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Store ID] [uniqueidentifier] NULL,
[Rx Start Date] [date] NULL,
[Rx Expiration Date] [date] NULL,
[Licensed Prescriber] [varchar] (33) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User Ordering] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rx Not Prescribed by Provider] [int] NOT NULL,
[PatName] [varchar] (122) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[birth_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[chart_id] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ssn] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rx Label] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Qty Written by Licensee] [int] NULL,
[Refills Remaining] [int] NULL,
[Original Refill Qty] [int] NULL,
[Pharmacy Name] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rx Location Name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEA Class] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Operation Type] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mmyy] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rx Non-Controlled] [int] NOT NULL,
[Rx Controlled] [int] NOT NULL,
[Rx Schedule I] [int] NOT NULL,
[Rx Schedule II] [int] NOT NULL,
[Rx Schedule III] [int] NOT NULL,
[Rx Schedule IV] [int] NOT NULL,
[Rx Schedule V] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [fdt].[Fact and Dim Medication] ADD CONSTRAINT [PK__Fact and__8327AB4B7510F7D9] PRIMARY KEY CLUSTERED  ([med_key]) ON [PRIMARY]
GO
