CREATE TABLE [fdt].[PHI Patient CHCN]
(
[MemberHSN] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ethnicity] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Language] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Current Age] [float] NULL,
[Cost Category] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cost Range] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Total Costs] [float] NULL,
[Trauma Costs] [float] NULL,
[Hep C Rx Costs] [float] NULL,
[Pharmacy Costs] [float] NULL,
[Inpatient Costs (POS 21) ] [float] NULL,
[ER Costs _(POS 23)] [float] NULL,
[Outpatient Costs_(POS 22)] [float] NULL,
[Office Costs_(POS 11)] [float] NULL,
[Other Costs_(All Other POS)] [float] NULL,
[Eligible in Current Month] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Current Month LOB] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Current Month Eligibility Category] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Current Month Delegate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Current Month PCP Clinic] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOB] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Eligibility Category] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aid Code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aid Code Description] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Delegate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IP Admits Last 6 Mo] [float] NULL,
[IP Admits Last 12 Mo] [float] NULL,
[ER Visits Last 6 Mo] [float] NULL,
[ER Visits Last 12 Mo] [float] NULL,
[Current Care Analyzer RUB (Resource Utilization Band)] [float] NULL,
[Current Open CMDM Case] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMDM Case Created Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Open CMDM w/in last 6 months] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2014 Member-Cost Analysis: Top 6% of Members] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2014 Member-Cost Analysis: Total Costs] [float] NULL
) ON [PRIMARY]
GO
