CREATE TABLE [fdt].[Dim Time]
(
[Key Date] [date] NOT NULL,
[MM-DD-YYYY] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YYYYMMDD] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Day of Month Date] [date] NULL,
[Long Day Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Year_sort] [datetime] NULL,
[Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Half_Year] [datetime] NULL,
[Half Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Quarter_sort] [datetime] NULL,
[Quarter] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Month_sort] [datetime] NULL,
[Month] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[week_sort] [datetime] NULL,
[Week] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Week - Monday] [date] NULL,
[Day_Of_Year] [int] NULL,
[Day of Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Day_Of_Half_Year] [int] NULL,
[Day of Half-Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Day_Of_Quarter] [int] NULL,
[Day of Quarter] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Day_Of_Month] [int] NULL,
[Day of Month] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Day_Of_Week] [int] NULL,
[Day of Week] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Week_Of_Year] [int] NULL,
[Week of Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Month_Of_Year] [int] NULL,
[Month of Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Month_Of_Half_Year] [int] NULL,
[Month of Half Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Month_Of_Quarter] [int] NULL,
[Month of Quarter] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Quarter_Of_Year] [int] NULL,
[Quarter of Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Quarter_Of_Half_Year] [int] NULL,
[Quarter of Half Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Half_Year_Of_Year] [int] NULL,
[Half Year of Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Year] [datetime] NULL,
[Fiscal Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Half_Year] [datetime] NULL,
[Fiscal Half Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Quarter] [datetime] NULL,
[Fiscal Quarter] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Month] [datetime] NULL,
[Fiscal Month] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Week] [datetime] NULL,
[Fiscal Week] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Day] [datetime] NULL,
[Fiscal Day] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Day_Of_Year] [int] NULL,
[Fiscal Day OF Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Day_Of_Half_Year] [int] NULL,
[Fiscal Day of Half Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Day_Of_Quarter] [int] NULL,
[Fiscal Day of Quarter] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Day_Of_Month] [int] NULL,
[Fiscal Day of Month] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Day_Of_Week] [int] NULL,
[Fiscal Day of Week] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Week_Of_Year] [int] NULL,
[Fiscal Week of Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Month_Of_Year] [int] NULL,
[Fiscal Month of Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Month_Of_Half_Year] [int] NULL,
[Fiscal Month of Half Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Month_Of_Quarter] [int] NULL,
[Fiscal Month OF Quarter] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Quarter_Of_Year] [int] NULL,
[Fiscal Quarter of Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Quarter_Of_Half_Year] [int] NULL,
[Fiscal Quarter of Half Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Half_Year_Of_Year] [int] NULL,
[Fiscal Half Year of Year ] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Relative Days to Today] [int] NULL,
[Relative Months to Today] [int] NULL,
[Relative Weeks to Today] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [fdt].[Dim Time] ADD CONSTRAINT [date_pk1] PRIMARY KEY CLUSTERED  ([Key Date]) ON [PRIMARY]
GO
