CREATE TABLE [fdt].[Dim Employee Hx]
(
[employee_key] [int] NOT NULL,
[employee_payroll_key] [int] NOT NULL,
[chart_account_key] [int] NULL,
[Pay Date] [date] NULL,
[Cost Number- Home] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cost Number- Worked In] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FTE Range Hx] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FTE_Range_hx_sort] [int] NOT NULL,
[FTE Allocated Range Hx] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FTE_Allocated_Range_hx_sort] [int] NOT NULL,
[Site Worked] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age Range Hx] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[age_range_hx_sort] [int] NOT NULL,
[Months since Hire Range Hx] [varchar] (27) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[months_since_start_range_hx_sort] [int] NULL,
[Months Since Hire Allocated Range Hx] [varchar] (27) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[months_since_start_allocated_range_hx_sort] [int] NULL,
[Hourly Rate Range Hx] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rate_range_hx_sort] [int] NULL,
[Salary Annualized Range Hx] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[salary_annualized_range_hx_sort] [int] NULL,
[Hourly Rate Hx] [decimal] (38, 6) NULL,
[Salary Annualized Hx] [decimal] (38, 6) NULL,
[Salary Actual Hx] [decimal] (38, 4) NULL,
[Age Hx] [int] NULL,
[Remaining Floating Hrs] [decimal] (38, 4) NULL,
[Remaining Holiday Hrs] [decimal] (38, 4) NULL,
[Remaining LTS Hrs] [decimal] (38, 4) NULL,
[Remaining Sick Hrs] [decimal] (38, 4) NULL,
[Remaining Vacation Hrs] [decimal] (38, 4) NULL,
[Months Since Hire Hx] [int] NULL,
[OSHPD Category] [varchar] (58) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
